# Generated by Django 5.2.8 on 2026-08-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
